/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BrandDelete: typeof import('./src/components/BrandDelete.vue')['default']
    BrandDeleteDialog: typeof import('./src/components/BrandDeleteDialog.vue')['default']
    BrandDialog: typeof import('./src/components/BrandDialog.vue')['default']
    CategoryDeleteDialog: typeof import('./src/components/CategoryDeleteDialog.vue')['default']
    CategoryDialog: typeof import('./src/components/CategoryDialog.vue')['default']
    copy: typeof import('./src/components/DeleteDialog copy.vue')['default']
    DeleteDialog: typeof import('./src/components/DeleteDialog.vue')['default']
    GoodDeleteDialog: typeof import('./src/components/GoodDeleteDialog.vue')['default']
    GoodDialog: typeof import('./src/components/GoodDialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImagesDialog: typeof import('./src/components/ImagesDialog.vue')['default']
    LoginModal: typeof import('./src/components/LoginModal.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PurchaseDialog: typeof import('./src/components/PurchaseDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserDeleteDialog: typeof import('./src/components/UserDeleteDialog.vue')['default']
    UserDialog: typeof import('./src/components/UserDialog.vue')['default']
  }
}
